emotion: Fix missing include resulting in unknown type GstNavigationCommand
At least on the gstreamer1 version in Fedora 19 this include is needed. Glima
reported it as well and I think he also uses Fedora.

modules/emotion/gstreamer1/emotion_gstreamer.c:643:4: error: unknown type name
'GstNavigationCommand'

Even if other distros or gstreamer1 versions do not need this it should be safe
to add it here.

Signed-off-by: Stefan Schmidt <s.schmidt@samsung.com>

Added Author as Signed-Off to push to review.tizen.org

Origin: http://git.enlightenment.org/core/efl.git/commit/?id=a440c8da275600cffa142ca99b611cf9faf7bdad
Bug-Tizen: TIVI-2578/part (Enable to build newest EFL 1.8 on IVI)
Bug-Tizen: PTREL-626/part (efl should support gstreamer 1.0)
Change-Id: Ifa6987b586d54ab07b949130b9e3dbf907067362
Signed-off-by: Philippe Coval <philippe.coval@open.eurogiciel.org>